# Generated by Django 5.1.4 on 2024-12-18 16:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='v1734539044/user.png', max_length=255, null=True, verbose_name='attachment'),
        ),
    ]
