# Generated by Django 5.1.4 on 2024-12-18 16:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='v1734540380/user.png', max_length=255, null=True, verbose_name='attachment'),
        ),
    ]
