# Generated by Django 5.1.4 on 2024-12-23 18:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esim', '0003_rename_validity_esimplan_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('BANK', 'Bank Transfer'), ('WALLET', 'Wallet')], default='CARD', max_length=20)),
                ('payment_gateway', models.CharField(default='Stripe', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='esim.esimplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
