# Generated by Django 5.1.4 on 2024-12-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_ref_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='price',
        ),
    ]
