# Generated by Django 5.1.4 on 2024-12-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_payment_date_created_payment_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='expiry_date',
            new_name='expiry_datetime',
        ),
    ]
