# Generated by Django 5.1.4 on 2024-12-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_rename_expiry_date_payment_expiry_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
