# Generated by Django 5.1.4 on 2025-10-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_payment_mpgs_success_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="mpgs_order_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="mpgs_order_currency",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="mpgs_session_version",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
