# Generated by Django 5.1.4 on 2024-12-23 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='esimplan',
            old_name='validity',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='esimplan',
            old_name='data_limit',
            new_name='volume',
        ),
        migrations.AddField(
            model_name='esimplan',
            name='activated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esimplan',
            name='currency_code',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esimplan',
            name='duration_unit',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esimplan',
            name='expires_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esimplan',
            name='package_code',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esimplan',
            name='slug',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esimplan',
            name='sms_status',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esimplan',
            name='speed',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esimplan',
            name='support_top_up_type',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esimplan',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='eSIMActivation',
        ),
    ]
