# Generated by Django 5.1.4 on 2024-12-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_payment_plan'),
        ('esim', '0003_rename_validity_esimplan_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimplan',
            name='payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='esim_plans', to='billing.payment'),
            preserve_default=False,
        ),
    ]
