# Generated by Django 5.1.4 on 2024-12-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0004_esimplan_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimplan',
            name='esim_status',
            field=models.CharField(default='PAID', max_length=25),
        ),
        migrations.AddField(
            model_name='esimplan',
            name='smdp_status',
            field=models.CharField(default='RELEASED', max_length=25),
        ),
    ]
