# Generated by Django 5.1.4 on 2024-12-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0006_remove_esimplan_sms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimplan',
            name='seller',
            field=models.CharField(default='esimaccess', max_length=25),
        ),
    ]
