# Generated by Django 5.1.4 on 2024-12-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0007_esimplan_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimplan',
            name='order_no',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
