# Generated by Django 5.1.4 on 2025-01-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0008_esimplan_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimplan',
            name='volume_left',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
