# Generated by Django 5.1.4 on 2025-01-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0009_esimplan_volume_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimplan',
            name='iccid',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
