# Generated by Django 5.1.4 on 2025-01-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0010_esimplan_iccid'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimplan',
            name='location_code',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
