# Generated by Django 5.1.4 on 2025-01-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0011_esimplan_location_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esimplan',
            name='iccid',
        ),
    ]
