# Generated by Django 5.1.4 on 2025-01-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0012_remove_esimplan_iccid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esimplan',
            old_name='volume_left',
            new_name='volume_used',
        ),
    ]
