# Generated by Django 5.1.4 on 2025-01-06 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0013_rename_volume_left_esimplan_volume_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimplan',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esimplan',
            name='activated_on',
            field=models.DateTimeField(),
        ),
    ]
