# Generated by Django 5.1.4 on 2025-01-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0014_esimplan_date_created_alter_esimplan_activated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esimplan',
            name='activated_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
