# Generated by Django 5.1.4 on 2025-01-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0016_alter_esimplan_volume_alter_esimplan_volume_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esimplan',
            name='volume',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='esimplan',
            name='volume_used',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
