# Generated by Django 5.1.4 on 2025-02-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0017_alter_esimplan_volume_alter_esimplan_volume_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimplan',
            name='iccid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
